# Generated by Django 3.2.16 on 2023-08-18 06:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexpair',
            name='symbol',
            field=models.CharField(blank=True, default='LIONTC', max_length=10, null=True),
        ),
    ]
