# Generated by Django 3.2.16 on 2023-08-19 07:54

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0002_alter_forexpair_symbol'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexpair',
            name='chart_data',
            field=jsonfield.fields.JSONField(),
        ),
    ]
