# Generated by Django 3.2.16 on 2023-08-21 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0005_alter_forexpair_chart_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forexpair',
            name='chart_data',
        ),
    ]
