# Generated by Django 3.2.16 on 2023-08-22 08:59

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0007_forexpair_chart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexpair',
            name='chart_data',
            field=jsonfield.fields.JSONField(default=list),
        ),
    ]
