# Generated by Django 3.2.16 on 2023-08-22 09:03

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0008_alter_forexpair_chart_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forexpair',
            name='chart_data',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
