# Generated by Django 3.2.16 on 2023-08-24 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0010_optiontrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='expired',
            field=models.BooleanField(default=False),
        ),
    ]
