# Generated by Django 3.2.16 on 2023-08-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0013_alter_optiontrade_stake'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='closing_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
