# Generated by Django 3.2.16 on 2023-08-24 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0014_alter_optiontrade_closing_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='stake',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
