# Generated by Django 3.2.16 on 2023-08-24 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0019_optiontrade_stake'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OptionTrade',
        ),
    ]
