# Generated by Django 3.2.16 on 2023-08-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0020_delete_optiontrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='OptionTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('stake', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expiration', models.PositiveSmallIntegerField()),
                ('option_type', models.CharField(max_length=4)),
                ('strike_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('closing_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('expired', models.BooleanField(default=False)),
            ],
        ),
    ]
