# Generated by Django 3.2.16 on 2023-08-24 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0021_optiontrade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiontrade',
            name='closing_price',
        ),
        migrations.RemoveField(
            model_name='optiontrade',
            name='stake',
        ),
    ]
