# Generated by Django 3.2.16 on 2023-08-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0022_auto_20230824_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='closing_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='optiontrade',
            name='stake',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
