# Generated by Django 3.2.16 on 2023-08-25 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0024_optiontrade_trader'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='optiontrade',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
