# Generated by Django 3.2.16 on 2023-08-28 10:08

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0026_alter_optiontrade_trader'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='close_time',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
