# Generated by Django 3.2.16 on 2023-09-13 07:52

from django.db import migrations
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0029_optiontrade_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='forexpair',
            name='candle_chart_data',
            field=jsonfield.fields.JSONField(blank=True, default=list, null=True),
        ),
    ]
