# Generated by Django 3.2.16 on 2023-09-18 07:19

from django.db import migrations, models
import jsonfield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0030_forexpair_candle_chart_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoPair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(blank=True, default='BTCUSD', max_length=10, null=True)),
                ('pair', models.CharField(blank=True, max_length=100, null=True)),
                ('candle_chart_data', jsonfield.fields.JSONField(blank=True, default=list, null=True)),
            ],
        ),
    ]
