# Generated by Django 3.2.16 on 2023-09-25 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0031_cryptopair'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiontrade',
            name='outcome',
        ),
        migrations.AlterField(
            model_name='optiontrade',
            name='close_time',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
