# Generated by Django 3.2.16 on 2023-10-14 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0033_optiontrade_outcome'),
    ]

    operations = [
        migrations.AddField(
            model_name='cryptopair',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
        migrations.AddField(
            model_name='forexpair',
            name='image',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
