# Generated by Django 3.2.16 on 2023-10-16 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0034_auto_20231014_0107'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='icon',
            field=models.ImageField(default=False, upload_to=''),
        ),
    ]
