# Generated by Django 3.2.16 on 2023-10-24 08:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('forex', '0035_trade_icon'),
    ]

    operations = [
        migrations.CreateModel(
            name='CryptoTrade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(default=False, upload_to='')),
                ('trade_direction', models.CharField(choices=[('BUY', 'Buy'), ('SELL', 'Sell')], max_length=4)),
                ('entry', models.DecimalField(decimal_places=4, default=False, max_digits=10)),
                ('take_profit', models.DecimalField(decimal_places=4, max_digits=10)),
                ('stop_loss', models.DecimalField(decimal_places=4, max_digits=10)),
                ('lot_size', models.DecimalField(decimal_places=2, max_digits=10)),
                ('equity', models.DecimalField(decimal_places=2, default=False, max_digits=10)),
                ('symbol', models.CharField(max_length=7)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('trader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
