# Generated by Django 3.2.16 on 2023-10-28 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0036_cryptotrade'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='countdown',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
