# Generated by Django 3.2.16 on 2023-10-28 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0037_optiontrade_countdown'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='close_exp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='optiontrade',
            name='countdown',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
