# Generated by Django 3.2.16 on 2023-10-28 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0038_auto_20231028_0058'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='countdown',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
