# Generated by Django 3.2.16 on 2023-10-28 08:43

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0040_alter_optiontrade_countdown'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='optiontrade',
            name='close_exp',
        ),
        migrations.AlterField(
            model_name='optiontrade',
            name='countdown',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 8, 48, 22, 861189, tzinfo=utc)),
        ),
    ]
