# Generated by Django 3.2.16 on 2023-10-28 08:45

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0041_auto_20231028_0143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='countdown',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 8, 44, 8, 796003, tzinfo=utc)),
        ),
    ]
