# Generated by Django 3.2.16 on 2023-10-28 11:35

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0042_alter_optiontrade_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='countdown',
            field=models.DateTimeField(default=datetime.datetime(2023, 10, 28, 11, 34, 57, 446360, tzinfo=utc)),
        ),
    ]
