# Generated by Django 3.2.16 on 2023-10-28 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0046_alter_optiontrade_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='close_time',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
