# Generated by Django 3.2.16 on 2023-10-30 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0048_auto_20231030_0705'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='countdown',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
