# Generated by Django 3.2.16 on 2023-10-30 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0052_alter_optiontrade_countdown'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='open_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
