# Generated by Django 3.2.16 on 2023-10-30 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0055_alter_optiontrade_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='close_time',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
