# Generated by Django 3.2.16 on 2023-10-30 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0058_alter_optiontrade_close_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='close_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
