# Generated by Django 3.2.16 on 2023-10-30 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0059_alter_optiontrade_close_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='time_now',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
