# Generated by Django 3.2.16 on 2023-10-30 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0060_optiontrade_time_now'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='time_now',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
