# Generated by Django 3.2.16 on 2023-10-31 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0063_auto_20231030_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trade',
            name='entry',
            field=models.DecimalField(decimal_places=5, default=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='stop_loss',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
        migrations.AlterField(
            model_name='trade',
            name='take_profit',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
