# Generated by Django 3.2.16 on 2023-11-01 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0064_auto_20231031_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='trade',
            name='assets_type',
            field=models.CharField(choices=[('FOREX', 'Forex'), ('CRYPTO', 'Crypto')], default='FOREX', max_length=10),
        ),
    ]
