# Generated by Django 3.2.16 on 2023-11-03 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0065_trade_assets_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CryptoTrade',
        ),
    ]
