# Generated by Django 3.2.16 on 2023-11-06 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0072_profile_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='account_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
