# Generated by Django 3.2.16 on 2023-11-06 21:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0073_profile_account_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='account_id',
            new_name='user_id',
        ),
    ]
