# Generated by Django 3.2.16 on 2023-11-07 06:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0074_rename_account_id_profile_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='optiontrade',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.account'),
        ),
        migrations.AlterField(
            model_name='trade',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.account'),
        ),
    ]
