# Generated by Django 3.2.16 on 2023-11-08 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0075_auto_20231107_0755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
