# Generated by Django 3.2.16 on 2023-11-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0076_alter_account_account_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='optiontrade',
            name='assets_type',
            field=models.CharField(choices=[('FOREX', 'Forex'), ('CRYPTO', 'Crypto')], default='FOREX', max_length=10),
        ),
    ]
