# Generated by Django 3.2.16 on 2023-11-18 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0079_bitcoinwallet_details'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bitcoinwallet',
            name='user',
        ),
        migrations.DeleteModel(
            name='Details',
        ),
        migrations.DeleteModel(
            name='BitcoinWallet',
        ),
    ]
