# Generated by Django 3.2.16 on 2023-11-19 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0081_bitcoinwallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='bitcoinwallet',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
