# Generated by Django 3.2.16 on 2023-11-19 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0082_bitcoinwallet_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
