# Generated by Django 3.2.16 on 2023-11-23 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0087_alter_bitcoinwallet_public_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='account_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
