# Generated by Django 3.2.16 on 2023-11-23 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0089_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='transaction_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
