# Generated by Django 3.2.16 on 2023-11-23 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('forex', '0091_auto_20231123_1340'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='trader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='forex.account'),
        ),
    ]
